src/objects/Alexa_Apps__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Callback_URL__c</fullName>
        <label>Callback URL</label>
        <type>Url</type>
    </fields>
    <label>Alexa Apps</label>
</CustomObject>

src/objects/Alexa_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Auth_Code_Grant__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Auth Code Grant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Debug__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Debug</label>
        <type>Checkbox</type>
    </fields>
    <label>Alexa Settings</label>
</CustomObject>

src/objects/RestLog__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Rest Log</label>
    <nameField>
        <displayFormat>RL-{YYYYMMDD}{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rest Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AlexaOAuthCallbackProxyController.cls
/*
    Author: Matthew Rumschlag
    Repository: https://github.com/mjrforce/appirio-alexa-sf
    Description: A Proxy between Salesforce Connected App and Amazon. Use VF page AlexaOAuthCallbackProxy as the connected apps callback url via sites.
*/
public class AlexaOAuthCallbackProxyController {

    public string getOnLoadAuthCode() {

        Alexa_Settings__c settings = Alexa_Settings__c.getOrgDefaults();

        if (settings.Auth_Code_Grant__c == true) {
            Map < String, String > params = apexPages.currentPage().getparameters();

            RestLog__c requestLog = new RestLog__c(Body__c = JSON.serializepretty(JSON.serializepretty(params)),
                Method__c = 'AlexaOAuthCallbackProxyController.getOnLoadAuthCode');

            try {

                string state = params.get('state');
                String key = state.substring(0, state.indexOf('-'));
                string returnstate = state.replace(key + '-', '');

                Alexa_Apps__c app = Alexa_Apps__c.getInstance(key);
                pagereference Page = new pagereference(app.callback_url__c);
                Page.getParameters().put('code', params.get('refresh_token'));
                Page.getParameters().put('state', returnstate);

                requestlog.Response__c = page.getURL();
                if (settings.enable_debug__c)
                    insert requestlog;
                return page.getURL();
            } catch (exception e) {
                requestlog.exception__c = e.getmessage();
                if (settings.enable_debug__c)
                    insert requestlog;
                return null;
            }
        } else {
            return null;
        }
    }
    @remoteaction
    public static string onLoadHash(string params) {

        //redirect uri configured in the Alexa Skill configuration
        Alexa_Settings__c settings = Alexa_Settings__c.getOrgDefaults();
        RestLog__c requestLog = new RestLog__c(Body__c = JSON.serializepretty(params),
            Method__c = 'AlexaOAuthCallbackProxyController.onLoadHash');

        try {
            system.debug(params);
            List < string > splitparams = params.split('&');
            system.debug(splitparams);
            map < string, string > mmap = new map < String, string > ();
            for (string s: splitparams) {
                mmap.put(s.substring(0, s.indexof('=')), s.substring(s.indexof('=') + 1));
            }
            string state = mmap.get('state');
            String key = state.substring(0, state.indexOf('-'));
            string returnstate = state.replace(key + '-', '');

            Alexa_Apps__c app = Alexa_Apps__c.getInstance(key);
            string url = app.callback_url__c;
            url += '#' + 'access_token=' + mmap.get('access_token');
            url += '&state=' + returnstate;
            url += '&token_type=Bearer';

            requestlog.Response__c = url;

            if (settings.enable_debug__c)
                insert requestlog;

            return url;

        } catch (exception e) {
            requestlog.exception__c = e.getmessage();
            if (settings.enable_debug__c)
                insert requestlog;
            return null;
        }

    }
}